image: docker

stages:
  - build

build:
  stage: build
  script:
    - docker build --pull -t registry.topthink.com/yunwuxin/php:$CI_COMMIT_REF_NAME --build-arg http_proxy=http://ss.kanclouds.cn:3128 --build-arg no_proxy=mirrors.aliyun.com .
    - docker push registry.topthink.com/yunwuxin/php:$CI_COMMIT_REF_NAME

