name: 8.0 swoole openresty
on:
  push:
    paths:
      - '.github/workflows/8.0-swoole-openresty.yml'
      - '8.0-swoole-openresty/**'
  workflow_run:
    workflows: [ "8.0 swoole" ]
    branches: [ main ]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./8.0-swoole-openresty
          push: true
          tags: |
            topthink/php:8.0-swoole-openresty
            registry.cn-shanghai.aliyuncs.com/topthink/php:8.0-swoole-openresty
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
