name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - "7.4"
      - "7.4-swoole"
      - "7.4-swoole-nginx"

jobs:

  build:

    runs-on: ubuntu-20.04
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: topthink/php:${{ steps.extract_branch.outputs.branch }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
